#!/bin/sh

script_name='.statistics.interface[] | select ( .network | test("Link") ) | .name '
script_ll_address='.statistics.interface[] | select ( .network | test("Link") ) | .address '
script_il_address='.statistics.interface[] | select ( .network | test("Link")|not ) | .address '

script_linklayer='.statistics.interface[] | select ( .network | test("Link") ) |
    "eth_recvd-pks=\(."received-packets");
    eth_recvd-errs=\(."received-errors");
    eth_recvd-bytes=\(."received-bytes");
    eth_sent-pks=\(."sent-packets");
    eth_send-errs=\(."send-errors");
    eth_sent-bytes=\(."sent-bytes");
    eth_dropped-pks=\(."dropped-packets");
    eth_colls=\(."collisions"); "
    '
script_iplayer='.statistics.interface[] | select ( .network | test("Link")|not ) |
    "ip_recvd-pks=\(."received-packets");
    ip_recvd-bytes=\(."received-bytes");
    ip_sent-pks=\(."sent-packets");
    ip_sent-bytes=\(."sent-bytes");"
    '

netstat_out=$( netstat -b -I vmx0 --libxo=json )

if_name=$( echo $netstat_out | jq -r "$script_name" )
ll_addr=$( echo $netstat_out | jq -r "$script_ll_address" )
il_addr=$( echo $netstat_out | jq -r "$script_il_address" )
ll_perf=$( echo $netstat_out | jq -r "$script_linklayer" )
il_perf=$( echo $netstat_out | jq -r "$script_iplayer" )

echo "OK Interface Perfdata of '$if_name'. MAC: $ll_addr, IP: $il_addr |" $ll_perf $il_perf
